
language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"

before_install:
  - npm install grunt-cli -g 
 
install:
  - npm install

before_script:
  - grunt build -v

notifications:
  email:
    on_success: always
    on_failure: always 

